### ISSUE TITLE
Add audiobook/ebook/physical book tag

### ISSUE THREAD

**Issue by IlyaasK** [fenimore/badreads#18]
I'd like to be able to remember whether I listened to or read the book, and read physical or audiobook.

**Comment by fenimore** [comment]
Makes sense to me, i wonder what i should call it, format ?

**Comment by buoyantair** [comment]
Format makes sense

**Comment by IlyaasK** [comment]
Agreed, format makes sense

**Comment by fenimore** [comment]
So version 0.2.2 (https://github.com/fenimore/badreads/releases/tag/v0.2.2) should be available soon on the Play store and F-droid. This will have the `format` field. Two things

1. When adding new books, this field will be filled in by OpenLibrary
2. When Editing a book, you can select "Fill in missing fields" to add it to an existing book


I'm going to close this ticket because I think this suffices. If you find that version 0.2.2 leaves something out, or is somehow broken, please reopen this issue (or another).

Thank you
